-- Quarto plano: Infinity - tudo do Advanced, sem teto de usuarios nem de ativos.
--
-- Limite NULO ja significa "sem limite" no sistema desde o inicio (e' o que acontece hoje
-- com quem esta sem plano). A diferenca e' que aqui isso e' uma escolha contratada, e nao
-- a ausencia de contrato: a tela passa a dizer "ilimitado no seu plano" em vez de "sua
-- empresa esta sem plano definido".
INSERT INTO "plans" ("id", "name", "description", "priceMonthly", "maxUsers", "maxInstruments", "features", "active", "createdAt")
SELECT '33333333-3333-4333-8333-333333333004', 'Infinity', 'Sem teto: usuarios e ativos ilimitados, com todos os recursos do Advanced. Para quem tem mais de uma planta ou nao quer conviver com limite.', 4997.00, NULL, NULL, ARRAY['Usuarios ilimitados', 'Ativos ilimitados', 'Cadastro e arvore de ativos', 'Solicitacoes de servico', 'OS corretivas e preventivas', 'Planos preventivos por tempo', 'Checklists e procedimentos', 'Historico do ativo', 'Dashboard operacional basico', 'Almoxarifado simples', 'Mao de obra e custo basico por OS', 'Planos preventivos por medidor', 'Programacao semanal e Kanban', 'HH planejada x realizada', 'Reserva e consumo de materiais', 'Custos por ativo, OS e area', 'Codigos de falha, Pareto e RCA', 'Backlog e aderencia a programacao', 'Importacao de dados', 'Relatorios gerenciais', 'Preditiva por pontos de medicao e limites configuraveis', 'Lubrificacao: lubrificantes, pontos, rotas, historico e previsao de consumo', 'Visao por planta, area e centro de custo', 'Paineis e indicadores avancados', 'Suporte prioritario', 'Integracoes futuras conforme disponibilidade tecnica']::text[], true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "plans" WHERE lower("name") = lower('Infinity'));

UPDATE "plans"
SET "description" = 'Sem teto: usuarios e ativos ilimitados, com todos os recursos do Advanced. Para quem tem mais de uma planta ou nao quer conviver com limite.', "priceMonthly" = 4997.00, "maxUsers" = NULL, "maxInstruments" = NULL,
    "features" = ARRAY['Usuarios ilimitados', 'Ativos ilimitados', 'Cadastro e arvore de ativos', 'Solicitacoes de servico', 'OS corretivas e preventivas', 'Planos preventivos por tempo', 'Checklists e procedimentos', 'Historico do ativo', 'Dashboard operacional basico', 'Almoxarifado simples', 'Mao de obra e custo basico por OS', 'Planos preventivos por medidor', 'Programacao semanal e Kanban', 'HH planejada x realizada', 'Reserva e consumo de materiais', 'Custos por ativo, OS e area', 'Codigos de falha, Pareto e RCA', 'Backlog e aderencia a programacao', 'Importacao de dados', 'Relatorios gerenciais', 'Preditiva por pontos de medicao e limites configuraveis', 'Lubrificacao: lubrificantes, pontos, rotas, historico e previsao de consumo', 'Visao por planta, area e centro de custo', 'Paineis e indicadores avancados', 'Suporte prioritario', 'Integracoes futuras conforme disponibilidade tecnica']::text[], "active" = true
WHERE lower("name") = lower('Infinity');
